GoogleCloudPlatform/solutions-modern-cicd-anthos

- README.md
- docs/index.md
Quick Start section missing, so linked to pre-req instead
In User Guide, fixed Installation link to point to pre-req and app creation instruction cleanup
> fixed add app instructions and quick start links

- 0_foundation/networks.tf
- 0_foundation/services.tf
- 0_foundation/versions.tf
- 1_clusters/clusters.tf
- 1_clusters/modules/anthos-platform-cluster/main.tf
- 1_clusters/outputs.tf
- 1_clusters/versions.tf
- 2_gitlab/gitlab-repos/repos.tf
- 2_gitlab/gitlab.tf
- 2_gitlab/outputs.tf
This updates the syntax for foundation and clusters to match 0.12 syntax and style. I also added registry-based version pinning for the GKE module.
> Clean up Terraform syntax/style

- starter-repos/hipster-loadgenerator/requirements.txt
@viglesiasce Dependabot wanted to bump hipster-loadgenerator's 'werkzeug' dependency version to 0.15.4, but I got an error in deployment, so I tested the latest 'werkzeug' version of 1.0.1 and deployment was successful. We can close PR #17 and merge this PR instead.
> Changed hipster-loadgenerator dependency 'werkzeug' to v1.0.1

- .gitignore
- 1_clusters/binary-auth.tf
- 1_clusters/modules/anthos-platform-cluster/main.tf
- 1_clusters/modules/anthos-platform-cluster/outputs.tf
- 1_clusters/variables.tf
- README.md
- cloudbuild-destroy.yaml
- tests/install.sh
Adding binary authorization after moving the infrastructure to a module in an upstream terraform project for reuse
This addition creates a policy that is set in DRY-RUN mode allowing images to be run on the cluster even if they fail the attestation requirements.
> Adding binary authorization baseline functionality to all clusters

- .gitignore
- cli/cmd/addApp.go
- cli/cmd/remove.go
- cli/cmd/removeApp.go
- cli/pkg/resources/acm.go
- cli/pkg/resources/ar.go
- cli/pkg/resources/gitlab.go
- cli/pkg/resources/iam.go
- cli/pkg/resources/wi.go
This adds `anthos-platform-cli remove app` to the CLI. When invoked with the name of an application, this results in the deletion of the following for the supplied app:
- All app repositories from GitLab, including ALL application source code
- All app images from GCP Artifact Registry, and the repository itself
- All app configuration data from the Anthos Config Management repository
- All running applications and any associated platform resources such as load balancers
When run, this subcommand displays a warning (that includes the above list) and prompts the user before continuing with the deletion.
> Implement app removal via CLI

- cli/Makefile
- cli/cmd/version.go
- cli/main.go
- cli/pkg/resources/version.go
Using the Git short-sha hash as a semver-label.  The "version" is currently hard-coded but the SHA hash is pulled in at build-time and passed to the main function, which sends to a delegate Version object for use by the Version command
> Adding a version command to the CLI 

- docs/index.md
Updating the anthos-platform-cli links in the documentation to pull the latest version.  This will help make maintenance of the cli binaries easier.
> Updating the anthos-platform-cli links to always grab latest.

- starter-repos/anthos-config-management/cluster/README.md
though it's embedded as users start making changes to the starter repos, this readme can be misleading as it's not specific to policy controller.
> this readme can be confusing, because this folder is acm specific

- starter-repos/golang-template/k8s/dev/deployment.yaml
Skaffold requires a GO* environment variable to be set in order to detect that an app can be debugged using the golang runtime.
> Add hint so that Skaffold recognizes go runtime

- 1_clusters/clusters.tf
This is to unblock an apparent issue with 3.29.0:
https://github.com/terraform-providers/terraform-provider-google/issues/6744
3.28.0 validated working to build clusters.
> Pin Terraform providers to a specific version

- 2_gitlab/versions.tf
This pins the Google Terraform providers in use for GitLab to work around an issue in 3.29.0:
https://github.com/terraform-providers/terraform-provider-google/issues/6744
> Pin TF provider

- 2_gitlab/gitlab.tf
- starter-repos/golang-template/.gitlab-ci.yml
- starter-repos/golang-template/skaffold.yaml
- starter-repos/java-template/.gitlab-ci.yml
- starter-repos/java-template/skaffold.yaml
- starter-repos/shared-ci-cd/skaffold/build.yaml
- starter-repos/shared-ci-cd/skaffold/render.yaml
This will leverage `skaffold render` to do the image build and manifest hydration for the main CI/CD pipelines. ATM I'm only switching over the java-template and golang-template. The other CI/CD snippets are going to left in place as they are used by other apps and I don't want to break those flows since they dont leverage Skaffold in all cases.
> Use skaffold to build and hydrate manifests

- test/setup/cloudbuild.yaml
cft tools container image was recently upgraded to Terraform 0.13.0.  Pinning that version at 0.12.0 until we upgrade across the board.
> Pinning the cft tools container version to 0.12.0

- ar-setup.sh
1) create an Artifact Registry repo if needed;
2) create a Google service account if needed, and grant the Google service account roles/artifactregistry.writer on the AR repo;
3) create and download a service account key;
4) add the AR repo and the service account key into the app project as GitLab project variables.
> Add a bash script for setting up Artifact Registry (AR) repository

- 3_acm/config-management.yaml.tpl
- 3_acm/install_acm.sh
- 3_acm/root-sync.yaml.tpl
- docs/index.md
- starter-repos/anthos-config-management/cluster/app-operator-role.yaml
- starter-repos/anthos-config-management/cluster/configsync-reconciler-role.yaml
- starter-repos/anthos-config-management/namespaces/app-environment/namespace.yaml
- starter-repos/anthos-config-management/namespaces/app-environment/rolebinding.yaml
- starter-repos/anthos-config-management/namespaces/managed-apps/go-app/namespace.yaml
- starter-repos/anthos-config-management/namespaces/managed-apps/go-app/rolebinding.yaml
This change uses a different approach from the one in https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/pull/104.
It uses the CSMR with `enableLegacyFields: false`. As a result, we need to create a `RootSync` for a new cluster.
> Update ACM repo and the steps for adding new clusters

- starter-repos/app-template/appctl/prepare.yaml
- starter-repos/app-template/appctl/validate.yaml
- starter-repos/app-template/config/base/patch-deployment.yaml
- starter-repos/app-template/config/envs/prod-central/kustomization.yaml
- starter-repos/app-template/config/envs/prod-east/kustomization.yaml
- starter-repos/app-template/config/envs/staging-west/deployment.yaml
- starter-repos/app-template/config/envs/staging-west/kustomization.yaml
- starter-repos/app-template/skaffold-ci.yaml
- starter-repos/app-template/skaffold/render.yaml
- Since the staging cluster created is in us-west. So I moved the environment to staging-west.
- Updated the namespace to `go-app`, which is managed by the root repo.
- Fixed a bug in the deployment patch file.
> move staging-central to staging-west

- ar-setup.sh
1) Remove the --project flag: allowing the user to specify a different
GCP project does not work well with the demo flow;
2) add a successful-setup message;
3) enhance the flag description of `--gitlab-access-token`.
> Tiny fixes

- starter-repos/app-template/appctl/prepare.yaml
- starter-repos/app-template/appctl/validate.yaml
The pipeline runs `appctl init` to get the appctl configuration of the
pre-initialized application. It will use the environment namespace
defined in the appctl configuration file for hydration.
> Pass the env-namespace in the validate/prepare stage

- ar-setup.sh
`expr` in Linux is generally GNU expr. Mac OS X uses BSD expr which
does not have the index command.
> Avoid using `expr index`, which does not work on Mac.

- README.md
- test/install.sh
Since Terraform is already trying to enable the APIs but there is a timing issue, I've added the gcloud commands to enable them before running the setup scripts.  This should help to reduce the likelihood of hitting the Secrets Manager API not enabled error condition (Issue #127).
> Adding commands to enable Binary Authorization and Secrets Manager to README

- README.md
Cloud Build failed to complete project setup without Secret Manager enabled.
> Include enabling Secret Manager API in README

- starter-repos/golang-template/Dockerfile
- starter-repos/golang-template/go.mod
In the current version of Golang a go.mod is expected.  Adding a go.mod to the starter repo, so the starter is still a functioning application.  Going forward application teams would then be responsible for keeping their individual go.mod files current and up to date.
> Updating the golang template for new module requirements.

- docs/index.md
Updating the documentation with instructions on how to build the anthos-platform-cli tool instead of download.
> Updating the docs with instructions on how to build the cli
